//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Polinomio.java
//  @ Date : 8/30/2021
//  @ Author : CODERS
//Sofia Montoya 566646, Cristina Isabel 565371, Manuel Sedano 621965, Jesus Izaguirre

//OBJ: evalaur un polinomio que reciba 4 parametros: ax^2+bx+c
import java.io.*;
import java.text.*;
import java.util.*;

public class Polinomio{
	private float a;
	private float b;
	private float c;
	private float x;
	
	
	public Polinomio(float a, float b,float c,float x){//metodo constructor
    this.a=a;
    this.b=b;
    this.c=c;
    this.x=x;
	}
	
	public double calcularPol() {//evaluar el polonimio
    return a*Math.pow(x,2)+b*x+c;
	}
   public String toString() {//imptimit resultado
     DecimalFormat d=new DecimalFormat("0.00");
     return "Su resultado es "+d.format(calcularPol());
   }

}

class Principal{
  public static void main(String args[]){
    float a,b,c,x;//crear variables
    String mensaje="Ingrese el valor de a:";//pedir los valores de cada variable
    a=pedirValor(mensaje);
    mensaje="Ingrese el valor de b:";
    b=pedirValor(mensaje);
    mensaje="Ingrese el valor de c:";
    c=pedirValor(mensaje);
    mensaje="Ingrese el valor de x:";
    x=pedirValor(mensaje);
    Polinomio p1=new Polinomio(a,b,c,x);//crear objeto
    System.out.println(p1);//mandar imprimir resultado
  }
  
   public static float pedirValor(String mensaje){//pedir valor
     Scanner s=new Scanner(System.in);
     boolean resultado;
     String val;
     do{        
        System.out.println(mensaje);
        val=s.next();
        try {                       //checar si es numerico
            Float.parseFloat(val);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;   
        }
        System.out.println("El valor ingresado debe ser numerico\n");
     }while(resultado==false);
    float valor = Float.parseFloat(val);
    return valor;
   }   
}
  